### ISSUE TITLE
non case sensitive file systems

### ISSUE THREAD

**Issue by beagleboys** [mwarning/docker-openwrt-builder#2]
first of all thank you for the great work. literally saved me hours of work.
Only change I would make is to add language in the readme to create a case sensitive disk image to work on when using this docker if you are working on a non case sensitive os.
thanks again for the great work!

**Comment by mwarning** [comment]
Great to read! :-)

Can you tell me what to do?

**Comment by beagleboys** [comment]
I adapted instructions from the official openwrt page to prep macosx: https://openwrt.org/docs/guide-developer/easy.build.macosx

you create a disk image
`hdiutil create -size 20g -fs "Case-sensitive HFS+" -volname OpenWrt OpenWrt.dmg
hdiutil attach OpenWrt.dmg`

and then when you load the docker you use:
`docker run -v /volumes/openwrt:/home/user -it openwrt_builder /bin/bash`

et voilà!

(on MacOS, mileage may vary)

**Comment by mwarning** [comment]
Great! I will add it to the readme.

**Comment by mwarning** [comment]
https://github.com/mwarning/docker-openwrt-builder/commit/d016bb6b75a018505bd75475feb39f10c08864eb

Let me know if this correct or if you have improvements in mind.
