### ISSUE TITLE
missing rsync dependency

### ISSUE THREAD

**Issue by petiepooo** [mwarning/docker-openwrt-builder#4]
When using the alpine branch, I'm seeing (may also affect master branch):

> Build dependency: Please install 'rsync'
> 
> Prerequisite check failed. Use FORCE=1 to override.
> make: *** [/home/user/openwrt/include/toplevel.mk:180: staging_dir/host/.prereq-build] Error 1

**Comment by mwarning** [comment]
hi, can you check if adding rsync fixes the problem for you (for alpine)?

**Comment by petiepooo** [comment]
I ran 'sudo apk add rsync' and no longer get that error when running make.  However, alpine also has trouble building cmake.  I've switched to the main branch and am not having that issue...

**Comment by mwarning** [comment]
What version of OpenWrt did you try compile in the alpine branch?

**Comment by petiepooo** [comment]
I didn't specify any version, so whatever it builds by default.  How would I pick a version, fwiw?

**Comment by mwarning** [comment]
Well, I do not know..

**Comment by petiepooo** [comment]
It built 'SNAPSHOT, r17471-b6cbbbb6ef'

FWIW, I was hoping to build 21.02.0 (latest stable)..

**Comment by petiepooo** [comment]
An answer for the record: checkout a tagged commit in git befor running make menuconfig.  Eg: 'git checkout -b v21.02.0'

**Comment by petiepooo** [comment]
correction: the git checkout should be done before updating and installing the feeds.

**Comment by mwarning** [comment]
I thought you meant something a specific rsync version :>
